name: Build test

on:
  schedule:
    # Runs at 03:00 UTC on the 7, 14, 21 and 28th of every month
    - cron: '0 3 7,14,21,28 1-12 ?'
  push:
    #paths:
    #- '.github/workflows/builder.yml'
    branches:
    - 'main'
env:
  PAT: ${{ secrets.PAT }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt update -qqy
        sudo apt install git
        rm -rf .git
        git clone "$PAT"
        cd tcbuild
        bash ci.sh deps
        bash build-tc.sh
        cd ..
        rm -rf *
